CREATE TABLE MERCHANTS(
	MERCHANTS_ID NUMBER NOT NULL,
	MERCHANTS_NAME VARCHAR2(250) NOT NULL,
	MERCHANTS_CATEGORY VARCHAR2(250) NOT NULL,
	CONSTRAINT MERCHANTS_PK PRIMARY KEY (MERCHANTS_ID)
);


CREATE TABLE ONLINE_OFFER(
	OFFER_ID NUMBER NOT NULL,
	OFFER_NAME VARCHAR2(1000) NOT NULL,
	OFFER_DESCRIPTION CLOB,
	OFFER_LINK CLOB
	OFFER_COUPON_CODE VARCHAR2(100),
	MERCHANTS_ID NUMBER
	CONSTRAINT ONLINE_OFFER_PK PRIMARY KEY (OFFER_ID)
	CONSTRAINT ONLINE_OFFER_FK FOREIGN KEY (MERCHANTS_ID) REFERENCES MERCHANTS(MERCHANTS_ID)
);


CREATE TABLE GIFT_CARD(
	GIFT_CARD_ID NUMBER NOT NULL,
	GIFT_CARD_VALUE NUMBER NOT NULL,
	GIFT_CARD_CASHBACK NUMBER,
	GIFT_CARD_VALIDITY NUMBER NOT NULL,
	MERCHANTS_ID NUMBER,
	CONSTRAINT GIFT_CARD_PK PRIMARY KEY (GIFT_CARD_ID)
	CONSTRAINT GIFT_CARD_FK FOREIGN KEY (MERCHANTS_ID) REFERENCES MERCHANTS(MERCHANTS_ID)
);


CREATE TABLE USER(
	USER_ID NUMBER NOT NULL,
	USER_NAME VARCHAR2 NOT NULL,
	USER_EMAIL VARCHAR2 NOT NULL,
	USER_PASS VARCHAR2 NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);


CREATE TABLE USERS_CART(
	USER_ID NUMBER NOT NULL,
	USER_NAME VARCHAR2 NOT NULL,
	USER_EMAIL VARCHAR2 NOT NULL,
	USER_PASS VARCHAR2 NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);




CREATE TABLE PURCHASE_ORDER (
	PURCHASE_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    USER_NAME
    USER_EMAIL
	GIFT_CARD_ID NUMBER NOT NULL,
    TIME_STAMP DATE,
    STATUS
	CONSTRAINT PURCHASE_ORDER_PK PRIMARY KEY (PURCHASE_ID)
);